### PR TITLE
Make Portable setting by default

### PR DESCRIPTION
**Pull request by megapro17**
Don't see any reason to keep this disabled. Didn't cause any problems, and who wants trash in their appdata folder?

### CODE REVIEW

**Comment by FailedShack** [comment]
The most common way to set-up the launcher is through [USBHelperInstaller](https://github.com/FailedShack/USBHelperInstaller), which defaults to `%AppData%\USBHelperLauncher`.
In this case, this doesn't really change anything as their data is still kept in `%AppData%`.
If you opt for installing manually, taking the time to modify the config file just takes a couple seconds. As it stands, I don't think there's enough reason to justify this change.

**Comment by megapro17** [comment]
So maybe you'll create two different variants, one is portable and other is not?

**Comment by FailedShack** [comment]
Well.. I kind take a manual installation as the de facto portable variant.
However, with the possible advent of an auto updater, soon USBHelperLauncher may need to know whether or not it actually lives in an installed version. So the `Portable` option could change based on that. Need to think about it.

**Comment by FailedShack** [comment]
Superseded by #68 (use `--portable` to accomplish this)

**Pull request closed without merging**
